In [2]:

import pickle
import pandas as pd
from ete3 import NCBITaxa
from tqdm import tqdm
import numpy as np

In [10]:
# /scratch/suyuelyu/deimm/data/oma/metadata_all_w_seq.parquet
all_meta = pd.read_parquet('/scratch/suyuelyu/deimm/data/oma/metadata_all.parquet')
all_meta.head()

      protein    taxid                         lineage       og
0  ARCGX00001  1579367  [131567, 2157, 93506, 1579367]  1220080
1  ARCGX00005  1579367  [131567, 2157, 93506, 1579367]   962367
2  ARCGX00007  1579367  [131567, 2157, 93506, 1579367]   775166
3  ARCGX00008  1579367  [131567, 2157, 93506, 1579367]  1189658
4  ARCGX00009  1579367  [131567, 2157, 93506, 1579367]   963202

In [11]:
# get full lineage at all standard ranks
ncbi = NCBITaxa()
std_ranks = ['domain', 'phylum', 'class', 'order', 'family', 'genus', 'species']
# get std rank for uniq taxid
def get_std_rankid(taxid):
    lineage = ncbi.get_lineage(taxid)
    ranks = ncbi.get_rank(lineage)
    std_ranks_dict = {ranks[t]: t for t in lineage if ranks[t] in std_ranks}
    return std_ranks_dict
uniq_taxids = all_meta['taxid'].unique()
taxid_to_std_ranks = {taxid: get_std_rankid(taxid) for taxid in uniq_taxids}

/scratch/suyuelyu/deimm/deimm/.venv/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2670412 was translated into 2666348
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/scratch/suyuelyu/deimm/deimm/.venv/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 2052317 was translated into 3107663
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/scratch/suyuelyu/deimm/deimm/.venv/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1081105 was translated into 1649241
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/scratch/suyuelyu/deimm/deimm/.venv/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 1064592 was translated into 27288
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))
/scratch/suyuelyu/deimm/deimm/.venv/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py:243: UserWarning: taxid 237631 was translated into 5270
  warnings.warn("taxid %s was translated into %s" %(taxid, merged_conversion[taxid]))

In [12]:
# save taxid_to_std_ranks as pickle
with open('/scratch/suyuelyu/deimm/data/oma/taxid_to_std_ranks.pkl', 'wb') as f:
    pickle.dump(taxid_to_std_ranks, f)

In [16]:
# check if anything is missing species rank
missing_species = [taxid for taxid, ranks in taxid_to_std_ranks.items() if 'species' not in ranks]
print(f"Taxids missing species rank: {missing_species}")

Taxids missing species rank: []

In [49]:
for rank in tqdm(std_ranks):
    all_meta[rank] = all_meta['taxid'].apply(lambda x: taxid_to_std_ranks[int(x)].get(rank, np.nan))
all_meta.head()

100%|██████████| 7/7 [00:35<00:00,  5.03s/it]

,protein,taxid,lineage,og,domain,phylum,class,order,family,genus,species
0,ARCGX00001,1579367,"[131567, 2157, 93506, 1579367]",1220080,2157,NaN,NaN,NaN,NaN,NaN,1579367
1,ARCGX00005,1579367,"[131567, 2157, 93506, 1579367]",962367,2157,NaN,NaN,NaN,NaN,NaN,1579367
2,ARCGX00007,1579367,"[131567, 2157, 93506, 1579367]",775166,2157,NaN,NaN,NaN,NaN,NaN,1579367
3,ARCGX00008,1579367,"[131567, 2157, 93506, 1579367]",1189658,2157,NaN,NaN,NaN,NaN,NaN,1579367
4,ARCGX00009,1579367,"[131567, 2157, 93506, 1579367]",963202,2157,NaN,NaN,NaN,NaN,NaN,1579367

In [ ]:
# $SCRATCH/mmseqs/bin/mmseqs easy-linclust /scratch/suyuelyu/deimm/data/oma/oma-seqs.fa /scratch/suyuelyu/deimm/data/oma/oma-seqs-linclust-50pident tmp --min-seq-id 0.5
# /scratch/suyuelyu/deimm/data/oma/oma-seqs-linclust-50pident_cluster.tsv
linclust_df = pd.read_csv('/scratch/suyuelyu/deimm/data/oma/oma-seqs-linclust-50pident_cluster.tsv', sep='\t', header=None, names=['rep_id', 'seq_id'])
# each cluster should have a cluster number starting from 0 to n clusters-1
n_clusters = linclust_df['rep_id'].nunique()

In [31]:
# add cluster id in descending order of cluster size
cluster_sizes = linclust_df['rep_id'].value_counts().sort_values(ascending=False)
cluster_id_mapping = {old_id: new_id for new_id, old_id in enumerate(cluster_sizes.index)}
linclust_df['cluster_id'] = linclust_df['rep_id'].map(cluster_id_mapping)
linclust_df.head()

       rep_id      seq_id  cluster_id
0  BRAM501876  BRAM501876     2269813
1  BRAM501876  RUMCH02411     2269813
2  BRAM501877  BRAM501877      716842
3  BRAM501877  BRAHW02137      716842
4  BRAM501877  BRAIP02462      716842

In [34]:
print(f"Number of clusters: {n_clusters}")

Number of clusters: 9718193

In [36]:
linclust_df['cluster_id'].value_counts().head()

cluster_id
0    1238
1    1125
2    1051
3    1049
4     964
Name: count, dtype: int64

In [37]:
all_meta.shape, linclust_df.shape

((15199426, 11), (22083295, 3))

In [ ]:
seq_id_to_cluster_id = dict(zip(linclust_df['seq_id'], linclust_df['cluster_id']))

In [51]:
all_meta["cluster_id"] = all_meta["protein"].map(seq_id_to_cluster_id)
all_meta.head()

,protein,taxid,lineage,og,domain,phylum,class,order,family,genus,species,cluster_id
0,ARCGX00001,1579367,"[131567, 2157, 93506, 1579367]",1220080,2157,NaN,NaN,NaN,NaN,NaN,1579367,6740521
1,ARCGX00005,1579367,"[131567, 2157, 93506, 1579367]",962367,2157,NaN,NaN,NaN,NaN,NaN,1579367,6740532
2,ARCGX00007,1579367,"[131567, 2157, 93506, 1579367]",775166,2157,NaN,NaN,NaN,NaN,NaN,1579367,6740530
3,ARCGX00008,1579367,"[131567, 2157, 93506, 1579367]",1189658,2157,NaN,NaN,NaN,NaN,NaN,1579367,6740529
4,ARCGX00009,1579367,"[131567, 2157, 93506, 1579367]",963202,2157,NaN,NaN,NaN,NaN,NaN,1579367,6740528

In [52]:
# remove any rows with NA in any of the std ranks then how many species and rows left?
all_meta_no_na = all_meta.dropna(subset=std_ranks, how='any')
print(f"Number of rows with no NA in std ranks: {len(all_meta_no_na)}")
print(
    f"Number of unique species with no NA in std ranks: {all_meta_no_na['species'].nunique()}"
)
# n clusters with no NA in std ranks?
print(f"Number of clusters with no NA in std ranks: {all_meta_no_na['cluster_id'].nunique()}"
)

Number of rows with no NA in std ranks: 13989546
Number of unique species with no NA in std ranks: 1908
Number of clusters with no NA in std ranks: 5276030

In [53]:
# save the all_meta with cluster_id to parquet
all_meta.to_parquet('/scratch/suyuelyu/deimm/data/oma/metadata_all_with_cluster.parquet', index=False)

In [71]:
# any og with multiple clusters?
og_cluster_counts = all_meta_no_na.groupby("og")["cluster_id"].nunique()
# any clusters with multiple ogs?
cluster_og_counts = all_meta_no_na.groupby("cluster_id")["og"].nunique()
print(f"Number of OGs with multiple clusters: {(og_cluster_counts > 1).sum()}")
print(f"Number of clusters with multiple OGs: {(cluster_og_counts > 1).sum()}")

Number of OGs with multiple clusters: 928942
Number of clusters with multiple OGs: 621655

In [67]:
# for each og get unique std ranks it covers and number of clusters
og_std_ranks = all_meta_no_na.groupby("og")[std_ranks].nunique()
og_cluster_counts = all_meta_no_na.groupby("og")["cluster_id"].nunique()
# number of samples per og?
og_nsequences = all_meta_no_na.groupby("og")["protein"].nunique()
og_summary = pd.concat([og_std_ranks, og_cluster_counts.rename("cluster_count"), og_nsequences.rename("n_sequences")], axis=1)

In [ ]:
# sort decending by domain, then phylum, then class, then order, then family, then genus, then species,
og_summary_sorted = og_summary.sort_values(by=std_ranks, ascending=False)

In [69]:
# drop anything with single species coverage
og_summary_sorted_multi_species = og_summary_sorted[og_summary_sorted['species'] > 1]
og_summary_sorted_multi_species

,domain,phylum,class,order,family,genus,species,cluster_count,n_sequences
og,,,,,,,,,
1250885,3,82,182,378,654,1106,1747,198,2267
1146506,3,82,178,350,599,1015,1629,361,2138
953976,3,81,186,364,599,937,1347,133,1536
1238393,3,81,179,365,636,1060,1638,569,2065
1212410,3,81,175,376,661,1081,1730,299,2250
...,...,...,...,...,...,...,...,...,...
99965,1,1,1,1,1,1,2,1,3
99980,1,1,1,1,1,1,2,1,3
9999,1,1,1,1,1,1,2,2,2
99992,1,1,1,1,1,1,2,2,3
99997,1,1,1,1,1,1,2,2,3

In [70]:
for rank in std_ranks:
    # print n og with multi unique values for this rank
    n_og_multi_rank = (og_summary_sorted_multi_species[rank] > 1).sum()
    print(f"Number of OGs with multiple unique {rank}: {n_og_multi_rank}")
    n_og_single_rank = (og_summary_sorted_multi_species[rank] == 1).sum()
    print(f"Number of OGs with single unique {rank}: {n_og_single_rank}")

Number of OGs with multiple unique domain: 30555
Number of OGs with single unique domain: 1011761
Number of OGs with multiple unique phylum: 258647
Number of OGs with single unique phylum: 783669
Number of OGs with multiple unique class: 417618
Number of OGs with single unique class: 624698
Number of OGs with multiple unique order: 655774
Number of OGs with single unique order: 386542
Number of OGs with multiple unique family: 741709
Number of OGs with single unique family: 300607
Number of OGs with multiple unique genus: 868690
Number of OGs with single unique genus: 173626
Number of OGs with multiple unique species: 1042316
Number of OGs with single unique species: 0

In [129]:
val_test_og = []
seed = 351
n_per_group = 100
for i, rank in enumerate(std_ranks):
    # pick val test group with single R vs multi R
    og_single_rank = og_summary_sorted_multi_species[og_summary_sorted_multi_species[rank] == 1]
    if i > 0:
        # need to make sure multi R is within same R-1 group
        prev_rank = std_ranks[i-1]
        og_multi_rank = og_summary_sorted_multi_species[(og_summary_sorted_multi_species[rank] > 1) & (og_summary_sorted_multi_species[prev_rank] == 1)]
    else:
        og_multi_rank = og_summary_sorted_multi_species[og_summary_sorted_multi_species[rank] > 1]
    # rank both by n next rank
    if i < len(std_ranks) - 1:
        next_rank = std_ranks[i+1]
        og_single_rank = og_single_rank.sort_values(by=next_rank, ascending=False)
        og_multi_rank = og_multi_rank.sort_values(by=next_rank, ascending=False)
    else:
        og_single_rank = og_single_rank.sort_values(by=rank, ascending=False)
        og_multi_rank = og_multi_rank.sort_values(by=rank, ascending=False)

    # take top 1000 from each group to sample from
    og_single_rank = og_single_rank.head(500)
    og_multi_rank = og_multi_rank.head(500)
    
    # randomly sample 3 og from each group
    if len(og_single_rank) >= n_per_group:
        og_single_rank_sample = og_single_rank.sample(
            n=n_per_group, random_state=seed
        ).index.tolist()
        seed += 10
        val_test_og.append((rank, "single", og_single_rank_sample))
    if len(og_multi_rank) >= n_per_group:
        og_multi_rank_sample = og_multi_rank.sample(
            n=n_per_group, random_state=seed
        ).index.tolist()
        seed += 10
        val_test_og.append((rank, 'multi', og_multi_rank_sample))
val_test_og_df = pd.DataFrame(val_test_og, columns=['rank', 'group', 'ogs'])
val_test_og_flat = [og for rank, group, ogs in val_test_og for og in ogs]
meta_val_test = all_meta_no_na[all_meta_no_na["og"].isin(val_test_og_flat)]
meta_train = all_meta_no_na[~all_meta_no_na["og"].isin(val_test_og_flat)]
print(f"Number of val test sequences: {len(meta_val_test)}")
print(f"Number of val test OGs: {meta_val_test['og'].nunique()}")
print(f"Number of train sequences: {len(meta_train)}")
print(f"Number of train OGs: {meta_train['og'].nunique()}")
# cluster ids in val test set
val_test_cluster_ids = meta_val_test["cluster_id"].unique()
# how many seq i meta train have cluster ids in val test set?
n_train_with_val_test_cluster = (
    meta_train["cluster_id"].isin(val_test_cluster_ids).sum()
)
print(
    f"Number of training sequences with cluster ids in val test set: {n_train_with_val_test_cluster}"
)
# remove any training sequences with cluster ids in val test set
meta_train_no_cluster_leak = meta_train[
    ~meta_train["cluster_id"].isin(val_test_cluster_ids)
]
print(
    f"Number of training sequences after removing cluster leak: {len(meta_train_no_cluster_leak)}"
)
print(
    f"Number of training OGs after removing cluster leak: {meta_train_no_cluster_leak['og'].nunique()}"
)

Number of val test sequences: 286244
Number of val test OGs: 1255
Number of train sequences: 13703302
Number of train OGs: 1156312
Number of training sequences with cluster ids in val test set: 45548
Number of training sequences after removing cluster leak: 13657754
Number of training OGs after removing cluster leak: 1155981

In [130]:
val_test_og_df = pd.DataFrame(val_test_og, columns=["rank", "group", "ogs"])
val_test_og_df

       rank   group                                                ogs
0    domain  single  [770260, 930189, 1240134, 961038, 1238252, 122...
1    domain   multi  [1248695, 921722, 1236080, 1217811, 711362, 12...
2    phylum  single  [1239313, 343149, 341795, 1244090, 1215031, 81...
3    phylum   multi  [699505, 1203908, 960958, 960947, 1235292, 691...
4     class  single  [923689, 546708, 618759, 673331, 547234, 54583...
5     class   multi  [349252, 1238424, 941963, 1156219, 967819, 115...
6     order  single  [815076, 816970, 831377, 868566, 853980, 34230...
7     order   multi  [1183778, 413092, 364521, 415668, 355402, 9799...
8    family  single  [943028, 261321, 858258, 831030, 1171925, 8535...
9    family   multi  [151899, 3782, 12994, 1437, 973362, 2428, 1512...
10    genus  single  [451421, 357834, 978187, 453385, 349002, 34914...
11    genus   multi  [29262, 794944, 920220, 129497, 879015, 909104...
12  species   multi  [350889, 930403, 349146, 346111, 450142, 82678...

In [131]:
# get size of each og in val test set
val_test_og_to_og_size = all_meta_no_na.groupby("og")["protein"].nunique().to_dict()
val_test_og_df['og_size'] = val_test_og_df['ogs'].apply(lambda ogs: [val_test_og_to_og_size[og] for og in ogs])

In [132]:
val_test_og_df['min_og_size'] = val_test_og_df['og_size'].apply(lambda sizes: min(sizes))
val_test_og_df['max_og_size'] = val_test_og_df['og_size'].apply(lambda sizes: max(sizes))
val_test_og_df['mean_og_size'] = val_test_og_df['og_size'].apply(lambda sizes: np.mean(sizes))
val_test_og_df

,rank,group,ogs,og_size,min_og_size,max_og_size,mean_og_size
0,domain,single,"[770260, 930189, 1240134, 961038, 1238252, 122...","[493, 455, 502, 518, 1061, 107, 490, 1353, 480...",107,1353,572.30
1,domain,multi,"[1248695, 921722, 1236080, 1217811, 711362, 12...","[2118, 1620, 1988, 1239, 1477, 1433, 1662, 158...",460,2254,1337.25
2,phylum,single,"[1239313, 343149, 341795, 1244090, 1215031, 81...","[120, 142, 135, 135, 85, 42, 103, 109, 122, 14...",17,147,105.09
3,phylum,multi,"[699505, 1203908, 960958, 960947, 1235292, 691...","[524, 504, 515, 525, 476, 443, 535, 475, 567, ...",404,1489,544.40
4,class,single,"[923689, 546708, 618759, 673331, 547234, 54583...","[43, 59, 46, 54, 58, 47, 52, 58, 59, 60, 55, 5...",40,66,55.09
5,class,multi,"[349252, 1238424, 941963, 1156219, 967819, 115...","[136, 134, 133, 141, 133, 139, 139, 133, 133, ...",121,144,134.13
6,order,single,"[815076, 816970, 831377, 868566, 853980, 34230...","[12, 13, 18, 15, 16, 14, 15, 14, 13, 15, 18, 1...",10,136,18.49
7,order,multi,"[1183778, 413092, 364521, 415668, 355402, 9799...","[64, 67, 52, 64, 61, 52, 57, 53, 52, 63, 67, 5...",44,196,64.60
8,family,single,"[943028, 261321, 858258, 831030, 1171925, 8535...","[26, 16, 15, 14, 40, 15, 21, 16, 14, 16, 13, 1...",12,40,16.93
9,family,multi,"[151899, 3782, 12994, 1437, 973362, 2428, 1512...","[130, 23, 20, 24, 31, 22, 119, 73, 18, 65, 64,...",17,141,47.72
10,genus,single,"[451421, 357834, 978187, 453385, 349002, 34914...","[27, 27, 26, 28, 27, 25, 26, 24, 25, 25, 27, 2...",24,28,25.97
11,genus,multi,"[29262, 794944, 920220, 129497, 879015, 909104...","[33, 19, 24, 23, 21, 22, 32, 22, 21, 25, 22, 2...",18,86,28.52
12,species,multi,"[350889, 930403, 349146, 346111, 450142, 82678...","[26, 27, 25, 28, 26, 26, 26, 26, 27, 27, 26, 2...",24,28,26.19

In [133]:
# write val_test_og_df to parquet
val_test_og_df.to_parquet('/scratch/suyuelyu/deimm/data/oma/oma_probe_val_test_og_summary.parquet', index=False)

In [105]:
# read /scratch/suyuelyu/deimm/data/oma/metadata_all_w_seq.parquet
all_meta_w_seq = pd.read_parquet('/scratch/suyuelyu/deimm/data/oma/metadata_all_w_seq.parquet')

In [ ]:
# get sequence for val test train
protein_to_seq = dict(zip(all_meta_w_seq['protein'], all_meta_w_seq['seq']))
del all_meta_w_seq

In [134]:
# map to sequence for val test train
meta_val_test['seq'] = meta_val_test['protein'].map(protein_to_seq)
meta_train_no_cluster_leak['seq'] = meta_train_no_cluster_leak['protein'].map(protein_to_seq)

/tmp/ipykernel_2570994/2127024044.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta_val_test['seq'] = meta_val_test['protein'].map(protein_to_seq)
/tmp/ipykernel_2570994/2127024044.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta_train_no_cluster_leak['seq'] = meta_train_no_cluster_leak['protein'].map(protein_to_seq)

In [135]:
# filter for length within 1024
meta_val_test_filtered = meta_val_test[meta_val_test['seq'].str.len() <= 1024]
meta_train_filtered = meta_train_no_cluster_leak[meta_train_no_cluster_leak['seq'].str.len() <= 1024]
print(f"Number of val test sequences after length filter: {len(meta_val_test_filtered)}, number of val test OGs after length filter: {meta_val_test_filtered['og'].nunique()}")
print(f"Number of train sequences after length filter: {len(meta_train_filtered)}, number of train OGs after length filter: {meta_train_filtered['og'].nunique()}")

Number of val test sequences after length filter: 269845, number of val test OGs after length filter: 1223
Number of train sequences after length filter: 12007816, number of train OGs after length filter: 654722

In [136]:
# save meta_val_test_filtered
meta_val_test_filtered.to_parquet('/scratch/suyuelyu/deimm/data/oma/oma_probe_meta_val_test_l1024_all.parquet', index=False)
meta_train_filtered.to_parquet('/scratch/suyuelyu/deimm/data/oma/oma_probe_meta_train_l1024_all.parquet', index=False)

In [137]:
# randomly assign half ogs to val and half to test in val_test_og_df
val_test_og_df['val_og'] = val_test_og_df.apply(lambda row: np.random.choice(row['ogs'], size=len(row['ogs'])//5, replace=False).tolist(), axis=1)
val_test_og_df['test_og'] = val_test_og_df.apply(lambda row: [og for og in row['ogs'] if og not in row['val_og']], axis=1)
val_test_og_df

,rank,group,ogs,og_size,min_og_size,max_og_size,mean_og_size,val_og,test_og
0,domain,single,"[770260, 930189, 1240134, 961038, 1238252, 122...","[493, 455, 502, 518, 1061, 107, 490, 1353, 480...",107,1353,572.30,"[1183523, 1134259, 674793, 1216640, 913903, 12...","[770260, 930189, 1240134, 961038, 1238252, 122..."
1,domain,multi,"[1248695, 921722, 1236080, 1217811, 711362, 12...","[2118, 1620, 1988, 1239, 1477, 1433, 1662, 158...",460,2254,1337.25,"[1204620, 1199762, 1248561, 1240084, 950127, 9...","[1248695, 921722, 1236080, 711362, 1223147, 12..."
2,phylum,single,"[1239313, 343149, 341795, 1244090, 1215031, 81...","[120, 142, 135, 135, 85, 42, 103, 109, 122, 14...",17,147,105.09,"[1142060, 1178849, 1156196, 1212585, 1196471, ...","[1239313, 343149, 341795, 1215031, 814260, 794..."
3,phylum,multi,"[699505, 1203908, 960958, 960947, 1235292, 691...","[524, 504, 515, 525, 476, 443, 535, 475, 567, ...",404,1489,544.40,"[1244069, 960951, 1196418, 1219605, 889979, 96...","[699505, 1203908, 960958, 960947, 691037, 7616..."
4,class,single,"[923689, 546708, 618759, 673331, 547234, 54583...","[43, 59, 46, 54, 58, 47, 52, 58, 59, 60, 55, 5...",40,66,55.09,"[1189116, 975502, 628097, 645559, 628588, 8811...","[923689, 618759, 673331, 547234, 545838, 62980..."
5,class,multi,"[349252, 1238424, 941963, 1156219, 967819, 115...","[136, 134, 133, 141, 133, 139, 139, 133, 133, ...",121,144,134.13,"[343203, 1151131, 1238424, 1185400, 1139804, 1...","[349252, 941963, 1156219, 967819, 1152861, 906..."
6,order,single,"[815076, 816970, 831377, 868566, 853980, 34230...","[12, 13, 18, 15, 16, 14, 15, 14, 13, 15, 18, 1...",10,136,18.49,"[810379, 982919, 1245727, 410425, 418095, 3571...","[816970, 831377, 868566, 853980, 342303, 34462..."
7,order,multi,"[1183778, 413092, 364521, 415668, 355402, 9799...","[64, 67, 52, 64, 61, 52, 57, 53, 52, 63, 67, 5...",44,196,64.60,"[1189139, 975682, 979945, 1136429, 1194107, 34...","[1183778, 364521, 415668, 355402, 912318, 9549..."
8,family,single,"[943028, 261321, 858258, 831030, 1171925, 8535...","[26, 16, 15, 14, 40, 15, 21, 16, 14, 16, 13, 1...",12,40,16.93,"[902280, 943028, 47969, 997547, 548086, 562561...","[261321, 858258, 831030, 1171925, 853549, 9430..."
9,family,multi,"[151899, 3782, 12994, 1437, 973362, 2428, 1512...","[130, 23, 20, 24, 31, 22, 119, 73, 18, 65, 64,...",17,141,47.72,"[3500, 630, 1136288, 1174092, 151292, 3838, 15...","[151899, 3782, 12994, 1437, 973362, 2428, 8306..."
10,genus,single,"[451421, 357834, 978187, 453385, 349002, 34914...","[27, 27, 26, 28, 27, 25, 26, 24, 25, 25, 27, 2...",24,28,25.97,"[942082, 927762, 835475, 451049, 452628, 35309...","[451421, 357834, 978187, 453385, 349002, 34914..."
11,genus,multi,"[29262, 794944, 920220, 129497, 879015, 909104...","[33, 19, 24, 23, 21, 22, 32, 22, 21, 25, 22, 2...",18,86,28.52,"[35297, 923093, 37074, 723226, 980153, 30959, ...","[29262, 794944, 920220, 129497, 879015, 909104..."
12,species,multi,"[350889, 930403, 349146, 346111, 450142, 82678...","[26, 27, 25, 28, 26, 26, 26, 26, 27, 27, 26, 2...",24,28,26.19,"[346253, 355440, 906565, 355214, 346670, 89455...","[350889, 349146, 346111, 450142, 826787, 45320..."

In [138]:
meta_val = meta_val_test_filtered[meta_val_test_filtered['og'].isin(val_test_og_df['val_og'].explode())]
meta_test = meta_val_test_filtered[meta_val_test_filtered['og'].isin(val_test_og_df['test_og'].explode())]
print(f"Number of val sequences: {len(meta_val)}")
print(f"Number of val OGs: {meta_val['og'].nunique()}")
print(f"Number of test sequences: {len(meta_test)}")
print(f"Number of test OGs: {meta_test['og'].nunique()}")

Number of val sequences: 55982
Number of val OGs: 247
Number of test sequences: 216747
Number of test OGs: 986

In [140]:
# write meta_val and meta_test to parquet
meta_val.to_parquet('/scratch/suyuelyu/deimm/data/oma/oma_probe_meta_val_l1024_all.parquet', index=False)
meta_test.to_parquet('/scratch/suyuelyu/deimm/data/oma/oma_probe_meta_test_l1024_all.parquet', index=False)
val_test_og_df.to_parquet('/scratch/suyuelyu/deimm/data/oma/oma_probe_val_test_og_summary.parquet', index=False)

In [141]:
og_summary_sorted_multi_species_train = og_summary_sorted_multi_species[og_summary_sorted_multi_species.index.isin(meta_train_no_cluster_leak['og'])]
og_summary_sorted_multi_species_train

,domain,phylum,class,order,family,genus,species,cluster_count,n_sequences
og,,,,,,,,,
1250885,3,82,182,378,654,1106,1747,198,2267
1146506,3,82,178,350,599,1015,1629,361,2138
953976,3,81,186,364,599,937,1347,133,1536
1238393,3,81,179,365,636,1060,1638,569,2065
1212410,3,81,175,376,661,1081,1730,299,2250
...,...,...,...,...,...,...,...,...,...
99965,1,1,1,1,1,1,2,1,3
99980,1,1,1,1,1,1,2,1,3
9999,1,1,1,1,1,1,2,2,2
99992,1,1,1,1,1,1,2,2,3
99997,1,1,1,1,1,1,2,2,3

In [144]:
og_summary_sorted_multi_species_train = og_summary_sorted_multi_species_train[
    og_summary_sorted_multi_species_train["n_sequences"] > 10
]

In [ ]:
for rank in std_ranks:
    # print n og with multi unique values for this rank
    n_og_multi_rank = (og_summary_sorted_multi_species_train[rank] > 1).sum()
    print(f"Number of train OGs with multiple unique {rank}: {n_og_multi_rank}")
    n_og_single_rank = (og_summary_sorted_multi_species_train[rank] == 1).sum()
    print(f"Number of train OGs with single unique {rank}: {n_og_single_rank}")

Number of train OGs with multiple unique domain: 22244
Number of train OGs with single unique domain: 186449
Number of train OGs with multiple unique phylum: 103727
Number of train OGs with single unique phylum: 104966
Number of train OGs with multiple unique class: 145475
Number of train OGs with single unique class: 63218
Number of train OGs with multiple unique order: 186979
Number of train OGs with single unique order: 21714
Number of train OGs with multiple unique family: 194590
Number of train OGs with single unique family: 14103
Number of train OGs with multiple unique genus: 201512
Number of train OGs with single unique genus: 7181
Number of train OGs with multiple unique species: 208693
Number of train OGs with single unique species: 0

In [ ]:
# 1 TB // 84 MB (1024 aa, all 32 hidden, assuming 4 bytes per float)
1000_000_000_000 // 84_000_000  # 11904 groups max

11904

In [163]:
# down sample to 12k groups at same composiiton of single vs multi rank groups
target_n_ogs = 12000
seed = 3515
og_summary_sorted_multi_species_train_12k = []
for i, rank in enumerate(std_ranks):
    # pick val test group with single R vs multi R
    og_single_rank = og_summary_sorted_multi_species_train[
        og_summary_sorted_multi_species_train[rank] == 1
    ]
    if i > 0:
        # need to make sure multi R is within same R-1 group
        prev_rank = std_ranks[i - 1]
        og_multi_rank = og_summary_sorted_multi_species_train[
            (og_summary_sorted_multi_species_train[rank] > 1)
            & (og_summary_sorted_multi_species_train[prev_rank] == 1)
        ]
    else:
        og_multi_rank = og_summary_sorted_multi_species_train[
            og_summary_sorted_multi_species_train[rank] > 1
        ]
    # rank both by n next rank
    if i < len(std_ranks) - 1:
        next_rank = std_ranks[i + 1]
        og_single_rank = og_single_rank.sort_values(by=next_rank, ascending=False)
        og_multi_rank = og_multi_rank.sort_values(by=next_rank, ascending=False)
    else:
        og_single_rank = og_single_rank.sort_values(by=rank, ascending=False)
        og_multi_rank = og_multi_rank.sort_values(by=rank, ascending=False)

    # take top 1000 from each group to sample from
    # og_single_rank = og_single_rank.head(500)
    # og_multi_rank = og_multi_rank.head(500)

    ratio_single = len(og_single_rank) / len(og_summary_sorted_multi_species_train)
    n_single_sample = int(ratio_single * target_n_ogs)
    ratio_multi = len(og_multi_rank) / len(og_summary_sorted_multi_species_train)
    n_multi_sample = int(ratio_multi * target_n_ogs)
    og_single_rank_sample = og_single_rank.sample(n=n_single_sample, random_state=seed).index.tolist()
    seed += 10
    og_multi_rank_sample = og_multi_rank.sample(n=n_multi_sample, random_state=seed).index.tolist()
    seed += 10
    og_summary_sorted_multi_species_train_12k.append((rank, 'single', og_single_rank_sample))
    og_summary_sorted_multi_species_train_12k.append((rank, 'multi', og_multi_rank_sample))
og_summary_sorted_multi_species_train_12k_df = pd.DataFrame(og_summary_sorted_multi_species_train_12k, columns=['rank', 'group', 'ogs'])

In [165]:
og_summary_sorted_multi_species_train_12k_df['n_ogs'] = og_summary_sorted_multi_species_train_12k_df['ogs'].apply(len)
og_summary_sorted_multi_species_train_12k_df

       rank   group                                                ogs  n_ogs
0    domain  single  [736489, 1006143, 946840, 954763, 1145782, 124...  10720
1    domain   multi  [910335, 943346, 807559, 662723, 728767, 11986...   1279
2    phylum  single  [983443, 720450, 3852, 810452, 868426, 733186,...   6035
3    phylum   multi  [794108, 334679, 866911, 986359, 995436, 82532...   4685
4     class  single  [935688, 54394, 631611, 874895, 923647, 351912...   3635
5     class   multi  [974568, 711007, 1169295, 258334, 341992, 1158...   2400
6     order  single  [791713, 23980, 1162086, 986330, 452599, 82381...   1248
7     order   multi  [1167884, 981953, 835633, 1149768, 799184, 931...   2386
8    family  single  [658841, 160119, 28383, 849800, 8862, 1068196,...    810
9    family   multi  [853641, 156931, 901995, 42582, 890998, 126803...    437
10    genus  single  [862267, 142525, 453971, 82470, 84512, 55554, ...    412
11    genus   multi  [151861, 848766, 597758, 564013, 1136325, 7976...    398
12  species  single                                                 []      0
13  species   multi  [127903, 480184, 987563, 1146422, 862264, 9228...    412

In [166]:
# filter meta_train_no_cluster_leak for ogs in og_summary_sorted_multi_species_train_12k_df
meta_train_no_cluster_leak_12k = meta_train_no_cluster_leak[meta_train_no_cluster_leak['og'].isin(og_summary_sorted_multi_species_train_12k_df['ogs'].explode())]
# meta_train_no_cluster_leak_12k print number of sequences and ogs
print(f"Number of train sequences in 12k set: {len(meta_train_no_cluster_leak_12k)}")
print(f"Number of train OGs in 12k set: {meta_train_no_cluster_leak_12k['og'].nunique()}")

Number of train sequences in 12k set: 1235438
Number of train OGs in 12k set: 32358

In [171]:
# check if there is any species that exist only in val test set but not in train set
# train_species = set(meta_train_no_cluster_leak_12k['taxid'].unique())
# val_test_species = set(meta_val_test_filtered['taxid'].unique())
# species_only_in_val_test = val_test_species - train_species
# print(f"Number of species only in val test set: {len(species_only_in_val_test)}")

for rank in std_ranks:
    uniq_rank_train = set(meta_train_no_cluster_leak_12k[rank].unique())
    uniq_rank_val_test = set(meta_val_test_filtered[rank].unique())
    rank_only_in_val_test = uniq_rank_val_test - uniq_rank_train
    print(f"Number of {rank} only in val test set: {len(rank_only_in_val_test)}")
    # are val test ranks well supported in train set?
    # quantify by min number of sequences in train set for each uniq_rank_val_test
    min_seq_per_rank = meta_train_no_cluster_leak_12k[meta_train_no_cluster_leak_12k[rank].isin(uniq_rank_val_test)].groupby(rank)['protein'].nunique().min()
    print(f"Minimum number of sequences in train set for {rank} in val test set: {min_seq_per_rank}")

Number of domain only in val test set: 0
Minimum number of sequences in train set for domain in val test set: 19832
Number of phylum only in val test set: 0
Minimum number of sequences in train set for phylum in val test set: 10
Number of class only in val test set: 0
Minimum number of sequences in train set for class in val test set: 10
Number of order only in val test set: 0
Minimum number of sequences in train set for order in val test set: 10
Number of family only in val test set: 0
Minimum number of sequences in train set for family in val test set: 10
Number of genus only in val test set: 0
Minimum number of sequences in train set for genus in val test set: 10
Number of species only in val test set: 0
Minimum number of sequences in train set for species in val test set: 6

In [172]:
# save 12k meta train set to parquet
meta_train_no_cluster_leak_12k.to_parquet('/scratch/suyuelyu/deimm/data/oma/oma_probe_meta_train_l1024_12k_ogs.parquet', index=False)

In [ ]:
# /scratch/suyuelyu/deimm/data/oma/oma_probe_last_protein_hidden_val_0.pkl
with open('/scratch/suyuelyu/deimm/data/oma/oma_probe_last_protein_hidden_val_0.pkl', 'rb') as f:
    last_hidden_val = pickle.load(f)

In [5]:
last_hidden_val[0]["last_protein_hiddens"][0].shape

torch.Size([389, 1280])

In [6]:
len(last_hidden_val[0]["last_protein_hiddens"])

33

In [7]:
last_hidden_val[0]["last_protein_hiddens"][0].dtype

torch.float16

In [9]:
last_hidden_val[0]

{'og': '554213',
 'protein_names': ['MAIZE34157',
  'ORYPU00709',
  'SORBI16252',
  'AEGTS19004',
  'ORYRU00807',
  'ORYNI28476',
  'WHEAT55835',
  'SETVI34409',
  'ERATE13167',
  'MISSI29983',
  'ORYSJ00812',
  'ORYBR00715',
  'BRADI08444',
  'ORYSI00859',
  'HORVV62017',
  'SETIT17338',
  'AEGTA27536'],
 'last_protein_hiddens': [tensor([[ 0.0080, -0.0031, -0.0404,  ..., -0.0147, -0.0217,  0.0263],
          [ 0.0006, -0.0098, -0.0077,  ...,  0.0022,  0.0083, -0.0013],
          [-0.0256, -0.0162,  0.0476,  ...,  0.0563, -0.0053, -0.0463],
          ...,
          [-0.0008, -0.0070, -0.0166,  ..., -0.0461,  0.0049, -0.0215],
          [ 0.0006, -0.0098, -0.0077,  ...,  0.0022,  0.0083, -0.0013],
          [-0.0090,  0.2162, -0.0299,  ...,  0.0763,  0.0130,  0.0197]],
         dtype=torch.float16),
  tensor([[-0.2029,  0.2517, -0.0665,  ..., -0.1859,  0.0068,  0.3181],
          [-0.3252, -0.3699,  0.1536,  ..., -0.1803,  0.0611,  0.4434],
          [ 0.1560, -0.0131,  0.0885,  ..., -0.1786, -0.0698,  0.0356],
          ...,
          [-0.2756,  0.1385,  0.0548,  ..., -0.0346, -0.0602, -0.2194],
          [-0.3264, -0.3311,  0.0759,  ..., -0.1851,  0.0938,  0.4407],
          [ 0.1510, -0.0028, -0.0598,  ...,  0.1100, -0.2451,  0.4192]],
         dtype=torch.float16),
  tensor([[-0.1219,  0.0856, -0.3643,  ..., -0.1041, -0.0431,  0.2136],
          [-0.4404, -0.4873,  0.0568,  ...,  0.0330, -0.1926,  0.3044],
          [ 0.2571, -0.1377,  0.2478,  ..., -0.0023, -0.5957, -0.1843],
          ...,
          [ 0.0121, -0.4014,  0.0669,  ..., -0.2847, -0.4741, -0.0647],
          [ 0.1821, -1.0088, -0.1448,  ..., -0.0711, -0.4265,  0.3320],
          [ 0.5576, -0.6724, -0.2849,  ...,  0.0687, -0.6509,  0.4434]],
         dtype=torch.float16),
  tensor([[-1.8005e-02,  8.0078e-02, -5.2637e-01,  ...,  6.4819e-02,
            1.6602e-01,  2.8931e-01],
          [-4.2676e-01, -4.2676e-01, -1.6699e-01,  ...,  1.0266e-01,
           -1.0278e-01,  3.4326e-01],
          [ 2.1753e-01,  2.1497e-01,  2.7344e-01,  ...,  1.4551e-01,
           -4.2944e-01, -3.5498e-01],
          ...,
          [ 2.2449e-01, -4.1309e-01,  1.4331e-01,  ..., -1.9397e-01,
           -5.4688e-01, -2.3413e-01],
          [ 2.5366e-01, -1.0439e+00, -2.1631e-01,  ...,  7.6294e-04,
           -2.2424e-01,  5.2686e-01],
          [ 7.6123e-01, -8.0957e-01, -2.8662e-01,  ...,  2.9633e-02,
           -6.4355e-01,  4.9219e-01]], dtype=torch.float16),
  tensor([[ 0.3945,  0.0486, -0.7651,  ...,  0.0383, -0.1418,  0.2656],
          [-0.5166, -0.1421, -0.6709,  ...,  0.1520, -0.4194,  0.4580],
          [ 0.3069,  0.6528,  0.1700,  ..., -0.0458, -0.7588, -0.0474],
          ...,
          [ 0.2085, -0.3259,  0.1967,  ..., -0.3884, -0.7959,  0.2097],
          [ 0.1442, -0.9692, -0.4531,  ...,  0.1451, -0.6216,  0.7134],
          [ 0.6562, -1.1191, -0.5586,  ..., -0.6133, -1.1680,  1.1074]],
         dtype=torch.float16),
  tensor([[-0.0579, -0.2876, -1.8867,  ..., -0.0870, -0.0822,  1.0986],
          [-0.8110, -0.1564, -1.5625,  ..., -0.2578,  0.0444,  0.8281],
          [ 0.0369,  0.7568, -0.7290,  ..., -0.2778, -0.4651,  0.4314],
          ...,
          [ 0.0635, -0.5854, -0.0851,  ..., -0.5952, -0.7407,  0.4219],
          [-0.0540, -1.2588, -0.7686,  ...,  0.0474, -0.6733,  0.8701],
          [ 0.4207, -1.3740, -0.8027,  ..., -0.6714, -0.9604,  1.2373]],
         dtype=torch.float16),
  tensor([[-0.0773, -0.1538, -1.8711,  ..., -0.2462,  0.0857,  1.0625],
          [-0.8833, -0.0032, -1.4277,  ..., -0.3867,  0.3994,  0.9287],
          [ 0.0398,  0.6982, -0.7021,  ..., -0.2954, -0.2993,  0.5635],
          ...,
          [ 0.0492, -0.4075, -0.4622,  ..., -0.5732, -0.4724,  0.5630],
          [ 0.2778, -1.1357, -0.8320,  ...,  0.0045, -0.4790,  0.9746],
          [ 0.5522, -1.0498, -0.6914,  ..., -0.6509, -1.0576,  1.5918]],
         dtype=torch.float16),
  tensor([[ 0.0525,  0.4841, -2.0898,  ..., -0.5420,  0.3540,  0.4985],
          [-0.3184,  0.6987, -1.8682,  ..., -0.2556,  0.3142,  0.8706],
          [-0.1744,  0.8057, -0.5850,  ...,  0.1499, -0.1001,  0.4170],
          ...,
          [-0.0321, -0.1824, -0.5332,  ...,  0.0222,  0.0447,  0.3225],
          [ 0.2805, -1.0967, -0.7197,  ..., -0.2480,  0.0540,  0.7256],
          [ 0.1284, -0.7598, -0.7373,  ..., -0.7729, -0.8096,  1.6211]],
         dtype=torch.float16),
  tensor([[-0.0859, -0.1794, -2.8477,  ..., -0.4773,  0.2983,  0.7236],
          [ 0.0107,  0.4771, -2.1426,  ..., -0.3491,  0.1638,  0.8340],
          [-0.9009,  0.3794, -0.3965,  ...,  0.2266, -0.1528,  1.0566],
          ...,
          [-0.2683, -0.4487, -0.8818,  ...,  0.2207, -0.3657,  0.0581],
          [-0.0423, -1.1562, -0.6924,  ..., -0.1820,  0.2698,  0.6812],
          [ 0.1768, -0.9844, -0.7373,  ..., -0.7290, -0.8306,  1.5605]],
         dtype=torch.float16),
  tensor([[ 0.8506,  0.0527, -2.7695,  ..., -0.5415,  0.1495,  0.9639],
          [ 0.4009,  0.5127, -1.7744,  ..., -0.4082, -0.0215,  1.1172],
          [-0.5283,  0.4290, -0.4692,  ..., -0.2783, -0.4351,  1.0322],
          ...,
          [ 0.0430, -0.5410, -1.0684,  ...,  0.0278, -0.4165,  0.5029],
          [-0.1462, -0.8247, -0.4731,  ..., -0.3887,  0.1025,  0.9014],
          [ 0.2388, -0.6475, -1.0967,  ..., -0.9512, -1.1875,  1.6465]],
         dtype=torch.float16),
  tensor([[ 1.1865,  0.0688, -2.9707,  ...,  0.1932, -0.0413,  0.8721],
          [ 0.9185, -0.2039, -2.7090,  ..., -0.8003, -0.0493,  0.8423],
          [-0.4595,  0.0069, -0.5718,  ...,  0.0505, -0.2603,  1.4043],
          ...,
          [-0.5430, -0.3743, -1.6777,  ..., -0.2695, -0.8335, -0.1387],
          [ 0.6118, -0.4375,  0.1826,  ..., -0.3428,  0.4749,  0.9336],
          [-0.0150, -0.8252, -1.2949,  ..., -0.4883, -1.4189,  1.8281]],
         dtype=torch.float16),
  tensor([[ 1.7676, -0.3374, -3.0469,  ...,  0.6313, -0.2294,  0.4829],
          [ 1.0439, -0.4875, -2.3066,  ..., -0.5215, -0.6157,  1.2607],
          [-0.8555,  0.2251,  0.1235,  ...,  0.1292, -0.4402,  1.4111],
          ...,
          [ 0.2224, -0.0361, -1.4385,  ..., -0.2700, -0.7886, -0.2690],
          [ 0.6245, -0.2725,  0.4814,  ...,  0.1823,  0.4028,  0.5298],
          [-0.0220, -0.0758, -1.2246,  ...,  0.0261, -1.3447,  1.9854]],
         dtype=torch.float16),
  tensor([[ 1.9131e+00, -9.3994e-03, -3.8496e+00,  ...,  8.3887e-01,
           -2.5928e-01,  6.3672e-01],
          [ 1.1426e+00, -5.9473e-01, -2.0781e+00,  ..., -2.8052e-01,
           -1.0469e+00,  1.3418e+00],
          [-8.2031e-01,  3.1787e-01,  2.7588e-01,  ...,  2.9150e-01,
           -9.3945e-01,  1.3096e+00],
          ...,
          [-3.2959e-03, -1.0957e+00, -2.2695e+00,  ...,  7.1777e-02,
           -7.6514e-01, -5.5469e-01],
          [ 3.5400e-01, -9.6826e-01, -5.5481e-02,  ...,  6.0547e-01,
            3.6157e-01,  9.1064e-01],
          [-4.1846e-01, -1.2129e+00, -2.2676e+00,  ...,  5.4883e-01,
           -1.7314e+00,  1.5381e+00]], dtype=torch.float16),
  tensor([[ 3.4961, -1.8906, -5.4570,  ...,  0.9316,  0.1074,  3.5312],
          [ 1.7412, -1.6006, -3.9414,  ..., -1.1475, -0.9727,  3.2500],
          [-1.2402, -0.7803, -2.9648,  ..., -0.3193, -1.6328,  1.5391],
          ...,
          [ 0.6006, -1.5195, -3.8867,  ...,  0.1021, -2.8145,  0.4385],
          [ 0.7939, -2.2422, -1.9121,  ...,  1.1045, -0.4463, -0.2595],
          [-0.5400,  0.6167, -4.4414,  ...,  1.5820, -1.1914,  1.7793]],
         dtype=torch.float16),
  tensor([[ 3.5742, -1.2627, -6.5156,  ...,  2.0684, -0.9082,  3.1328],
          [ 1.7041, -1.4062, -4.6992,  ..., -1.4707, -2.4023,  2.7148],
          [-1.9062, -0.2500, -2.0684,  ..., -1.1572, -1.5059,  1.5117],
          ...,
          [-0.1583, -1.2051, -3.0547,  ..., -2.0215, -2.4805,  1.2070],
          [ 0.4434, -1.7148, -1.3438,  ...,  0.0000, -1.7305, -1.2129],
          [-0.9570,  0.8330, -4.1289,  ...,  1.7266, -1.2725,  2.1758]],
         dtype=torch.float16),
  tensor([[ 3.4844, -0.6787, -6.8906,  ...,  1.1758, -0.8086,  3.3457],
          [ 1.5703, -0.4263, -5.1016,  ..., -2.1426, -1.9629,  2.9062],
          [-1.4473,  0.5791, -2.3789,  ..., -1.8740, -0.3242,  1.3672],
          ...,
          [-0.2490, -0.9224, -2.8867,  ..., -2.3281, -2.0293,  1.5371],
          [ 0.4282, -1.8164, -1.4287,  ..., -0.4875, -1.3652, -1.6699],
          [-1.0908,  1.0605, -5.5000,  ...,  1.5723, -0.7373,  2.7422]],
         dtype=torch.float16),
  tensor([[ 5.7930, -1.8301, -6.9922,  ...,  1.1094, -0.5586,  4.5820],
          [ 4.7266, -0.3818, -5.1641,  ..., -3.6777, -2.6797,  5.5273],
          [-0.4385,  0.9980, -3.4219,  ..., -2.2227, -0.8726,  2.9922],
          ...,
          [-0.1748, -0.9604, -4.5586,  ..., -2.0664,  0.4243,  1.4170],
          [ 1.0430, -3.4609, -2.0625,  ..., -0.4397,  0.3960, -1.4736],
          [-1.4102,  1.5615, -4.8672,  ...,  0.6045,  0.5576,  3.4648]],
         dtype=torch.float16),
  tensor([[ 5.2383, -1.2578, -6.6797,  ...,  0.1724, -0.9707,  3.4180],
          [ 4.5273,  0.3484, -4.3125,  ..., -3.8242, -1.9189,  5.2383],
          [-0.2769,  0.8892, -2.5547,  ..., -1.9658,  0.2871,  2.2969],
          ...,
          [-0.8047, -0.5957, -4.7031,  ..., -1.8809,  0.5610,  0.9775],
          [ 0.0813, -3.3477, -1.9688,  ..., -0.3899,  1.1621, -1.3242],
          [-2.0996,  2.2637, -5.2617,  ...,  0.0732,  1.7266,  3.3691]],
         dtype=torch.float16),
  tensor([[ 6.4219, -3.2109, -7.6602,  ..., -1.8965, -2.5625,  2.9902],
          [ 5.7383, -1.3740, -4.2539,  ..., -4.5156, -2.9688,  5.5469],
          [-0.0361,  1.6934,  0.7441,  ..., -3.0078, -1.3535,  1.8535],
          ...,
          [-1.8281, -1.7559, -4.6250,  ..., -5.1758, -0.8027,  2.4648],
          [-2.5742, -1.9258, -0.9849,  ..., -1.8008,  1.5723,  3.1348],
          [-2.6289,  2.1250, -3.1328,  ..., -5.0898,  3.5508,  5.5078]],
         dtype=torch.float16),
  tensor([[ 5.9805, -3.0098, -8.6328,  ..., -1.7627, -3.2578,  3.3613],
          [ 5.4492, -1.5557, -6.7031,  ..., -4.3633, -4.1172,  5.7227],
          [ 0.1101,  1.7607, -0.4629,  ..., -2.2266, -0.6670,  3.6328],
          ...,
          [-3.1133, -1.5410, -3.2109,  ..., -4.7539, -1.2568,  2.7109],
          [-3.7246,  0.1123,  1.3926,  ..., -1.6465,  1.8184,  3.7656],
          [-5.1836,  1.8555, -1.4209,  ..., -3.8223,  3.6992,  4.8906]],
         dtype=torch.float16),
  tensor([[  5.7617,   0.5713, -11.0312,  ...,  -3.1680,  -4.2578,   7.8477],
          [  8.8516,   2.0352, -10.3906,  ...,  -4.4805,  -6.7969,  10.5000],
          [  1.0039,   4.0117,  -2.1562,  ...,  -3.6660,  -0.9004,   9.5234],
          ...,
          [ -3.0215,  -1.1406,  -5.8867,  ...,  -4.5625,  -1.1738,   5.0117],
          [ -0.2959,   1.3242,   0.0830,  ...,  -2.1914,   1.2051,  11.4531],
          [ -1.6084,   3.2520,  -4.5117,  ...,  -3.8828,   1.3926,  12.3047]],
         dtype=torch.float16),
  tensor([[ 1.2352e+01,  1.0312e+00, -1.3156e+01,  ...,  7.4609e-01,
            1.5303e+00,  1.1094e+01],
          [ 1.2562e+01,  1.9531e-03, -9.5391e+00,  ..., -1.1539e+01,
           -3.1641e-01,  1.4797e+01],
          [ 1.6318e+00,  2.9961e+00,  3.4082e+00,  ..., -1.1820e+01,
            4.7500e+00,  7.5312e+00],
          ...,
          [ 7.2109e+00, -8.9141e+00, -9.1953e+00,  ..., -1.8301e+00,
            3.7539e+00,  7.0625e+00],
          [-9.0820e-01, -9.3828e+00, -1.6113e+00,  ...,  1.1611e+00,
            8.7344e+00,  5.0664e+00],
          [ 1.6182e+00, -4.8750e+00, -1.3047e+00,  ...,  9.4141e-01,
            8.0625e+00,  5.5117e+00]], dtype=torch.float16),
  tensor([[ 12.6562,   2.8887, -16.2188,  ...,   4.2773,   0.5176,  15.3828],
          [  9.8906,   5.4609, -17.3281,  ..., -16.0156,  -6.2031,  19.6875],
          [  1.5771,  14.5469,   0.4551,  ..., -15.5625,   0.7676,   7.2344],
          ...,
          [  9.4062, -11.6328, -18.2500,  ...,  -0.1875,  -4.1680,  12.7031],
          [ -7.3945,  -1.2812,  -5.6172,  ...,  10.7656,   2.0117,   2.0703],
          [  1.5059,  -5.1250,  -1.3086,  ...,   6.3516,   4.7578,   2.0781]],
         dtype=torch.float16),
  tensor([[ 13.4844,   4.8945, -18.9375,  ...,   5.6875,  -2.0898,  15.2578],
          [ 11.3828,   6.4727, -22.0938,  ..., -15.9609,  -9.8984,  16.3281],
          [  2.7969,  15.5625,  -1.9238,  ..., -16.4531,   0.1797,   0.1797],
          ...,
          [ 10.1406,  -9.0625, -19.0781,  ...,  -1.9004,  -5.1953,   6.8906],
          [ -6.8750,  -0.5420,  -8.0703,  ...,   9.2422,  -0.8301,  -3.4824],
          [  1.5586,  -5.5547,  -3.1230,  ...,   7.1914,   5.4766,  -2.7051]],
         dtype=torch.float16),
  tensor([[ 14.2188,   0.8398, -14.4453,  ...,  10.0859,  -5.3438,  11.0625],
          [ 14.9141,   5.5234, -21.8750,  ..., -14.3984, -13.2344,  16.5938],
          [  1.0078,  14.1406,  -0.4453,  ..., -14.0000,  -6.1953,  -3.8672],
          ...,
          [ 13.2812, -17.2188, -17.8125,  ...,  -7.6016, -11.2734,   1.6562],
          [ -1.5352,   1.9590, -10.5312,  ...,  13.9375,  -3.9961,  -8.0703],
          [  1.6992, -10.1719,  -2.0879,  ...,   4.3594,   1.1699,  -5.9102]],
         dtype=torch.float16),
  tensor([[ 15.0938,   0.2437, -15.7578,  ...,  10.7266,  -5.8359,  11.6016],
          [ 17.2969,   8.0312, -20.7812,  ..., -13.0156, -11.8125,  17.9375],
          [  3.6230,  13.8594,   1.5078,  ..., -13.2188,  -7.5195,  -2.9355],
          ...,
          [ 13.5938, -18.0781, -20.2812,  ...,  -8.0781, -12.0938,   1.1064],
          [  0.9238,   2.4883,  -6.9922,  ...,  12.5391,  -6.3516,  -9.5234],
          [  1.2432, -11.2656,  -0.7935,  ...,   3.7266,   0.2056,  -3.3477]],
         dtype=torch.float16),
  tensor([[ 12.1094,   2.7109, -18.7500,  ...,  10.1562,  -8.1016,  15.5000],
          [ 14.4531,   7.6797, -26.0781,  ..., -16.4062, -11.1797,  23.4375],
          [  1.8164,  14.6484,  -1.1582,  ..., -17.5000,   1.4062,   1.9688],
          ...,
          [ 13.0781, -18.1094, -22.2188,  ..., -18.0000, -13.2344,   0.2764],
          [  3.2578,   2.5039,  -4.8633,  ...,   3.6172,  -2.3555, -16.3281],
          [  2.7715,  -3.8672,  -2.6523,  ...,   1.5361,  -2.1816,  -7.8750]],
         dtype=torch.float16),
  tensor([[ 12.9219,   1.8301, -20.9375,  ...,  11.7578,  -8.0234,  14.8984],
          [ 13.4531,   4.8711, -30.5625,  ..., -15.2812, -13.4766,  24.5000],
          [  4.8594,  13.3203,  -3.2441,  ..., -15.1875,   0.1650,   4.9297],
          ...,
          [ 16.0469, -19.5938, -24.3281,  ..., -15.4062, -15.2031,   4.9609],
          [  4.2344,  -4.2930,  -2.5137,  ...,   4.8359,  -4.0625, -16.2812],
          [  2.6094,  -8.6875,  -3.8184,  ...,   4.4062,  -3.9648,  -8.9453]],
         dtype=torch.float16),
  tensor([[ 19.3594,  -1.5322, -29.8281,  ...,  14.1875,  -8.6562,  33.0625],
          [ 14.8750,   1.1992, -42.2500,  ..., -14.8359, -12.2109,  23.5781],
          [ 12.1250,  13.2031,   0.3555,  ..., -18.6406,  -5.7070,   1.5039],
          ...,
          [ 20.1562, -23.2188, -28.2656,  ..., -10.5000,  -5.7383,   4.7734],
          [ 11.2734,  -4.7031,  -8.9844,  ...,  13.7656,  -3.8594, -19.3906],
          [ 11.5859, -21.2344,  -7.0234,  ...,  -2.1016,   1.6875, -17.2188]],
         dtype=torch.float16),
  tensor([[ 16.2969,   0.6943, -32.1562,  ...,  13.0938,  -4.1055,  36.0625],
          [ 12.8594,   0.1426, -40.9688,  ..., -17.5156,  -9.8438,  26.2656],
          [  8.7812,  13.3281,   1.5996,  ..., -25.1875,  -5.6328,   7.9648],
          ...,
          [ 18.7500, -24.5312, -30.4375,  ...,  -9.7344,  -8.6016,   9.2031],
          [ 10.7188, -11.5000, -12.5156,  ...,  14.3359,  -7.6641, -11.0625],
          [  7.8242, -26.7500,  -8.4219,  ...,  -1.2686,   0.0837, -11.4531]],
         dtype=torch.float16),
  tensor([[ 16.9844,  -6.3984, -32.8438,  ...,   9.2188,  -0.0469,  37.3125],
          [ 16.6406,  -4.8008, -46.6875,  ..., -20.0000,  -8.2266,  26.0625],
          [  8.1484,  13.6016,  -1.4268,  ..., -25.7188,  -6.7734,   9.0625],
          ...,
          [ 16.5469, -26.4531, -31.3281,  ...,  -4.4805,  -7.9102,   8.4219],
          [ 14.0703, -18.4844, -15.3281,  ...,   9.7031,  -6.5352, -10.7188],
          [  4.5469, -32.7500,  -6.9258,  ...,  -2.3652,   5.8164, -14.3359]],
         dtype=torch.float16),
  tensor([[  1.7773, -14.8750, -16.5938,  ...,  12.5625, -14.4219,  48.7188],
          [ 23.5469, -15.4219, -41.1875,  ..., -22.0000,  -9.4062,  36.6562],
          [ 26.4375,  -6.2734, -22.3125,  ..., -27.3125,  15.0938,  17.7188],
          ...,
          [ 10.2656, -37.2188, -36.7812,  ...,  -6.8594, -22.6562,  15.2500],
          [  6.7227, -20.6562,  -5.2812,  ...,   2.1055, -16.2812,  -0.8320],
          [-18.7500, -40.4062,  -1.1016,  ...,   2.0918,  -0.4609, -24.2500]],
         dtype=torch.float16),
  tensor([[ 0.1192, -0.2600, -0.6880,  ...,  0.3433, -0.4045,  0.9878],
          [ 0.0398, -0.4978, -0.8452,  ..., -0.4500,  0.0146,  0.6987],
          [-0.1716,  0.5405, -0.0927,  ..., -0.1716,  0.4519,  0.9849],
          ...,
          [-0.2434, -0.0283, -0.4670,  ...,  0.1011, -0.2705,  0.6099],
          [-0.4868, -0.5522, -0.3167,  ...,  0.0017, -0.1332,  0.1403],
          [-0.4773, -0.8779, -0.1947,  ...,  0.0555, -0.1015, -0.2405]],
         dtype=torch.float16)],
 'lin': np.int64(37682)}